name = "PublicJuliaRegistry"
uuid = "36a5c377-4d40-49e4-92cd-9a723194e489"
repo = "git@github.com:mattwigway/PublicJuliaRegistry.git"
description = "Matt Bhagat-Conway's public packages that aren't ready for General"

[packages]
b59920ca-ae83-47b1-a52c-d6d89e4b4b86 = { name = "OSRM", path = "O/OSRM" }
f9e57d04-be1f-4339-a529-971801331ddb = { name = "TransitRouter", path = "T/TransitRouter" }
